Repository berty/community, pull requests merged in 2020-04, with the labels that each got.

#62 Create 2020-03-30--staff-team-weekly-sync.md
  meeting-notes/2020/Q1/2020-03-30--staff-team-weekly-sync.md
Labels: 🔍 Ready for Review

#63 Create 2020-04-06--staff-team-weekly-sync.md
  meeting-notes/2020/Q2/2020-04-06--staff-team-weekly-sync.md
Labels: ✅ Approved

#64 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: ✅ Approved

#66 Create 2020-04-14--staff-team-weekly-sync.md
  meeting-notes/2020/Q2/2020-04-14--staff-team-weekly-sync.md
Labels: ✅ Approved, 🔍 Ready for Review

#68 feat: add meta AUTHORS file generation script
  .gitignore
  .mailmap
  AUTHORS
  scripts/gen-AUTHORS.sh
  scripts/repos.csv
Labels: ✅ Approved

#71 Create 2020-04-20--staff-team-weekly-sync.md
  meeting-notes/2020/Q2/2020-04-20--staff-team-weekly-sync.md
Labels: ✅ Approved

#70 feat: add README.md template
  README.md
  templates/README.md
Labels: 🔍 Ready for Review

#73 Create 2020-04-27--staff-team-weekly-sync.md
  meeting-notes/2020/Q2/2020-04-27--staff-team-weekly-sync.md
Labels: ✅ Approved

#74 chore: update AUTHORS list
  .mailmap
  AUTHORS
  scripts/gen-AUTHORS.sh
Labels: 🔍 Ready for Review
